monolog:
    channels: ["webhook"]
    handlers:
        webhook_handler:
            level:    debug
            type:     service
            # DEPENDS_ON_WEBHOOK_HANDLER_ID below
            id:       monolog.webhook_handler
            channels: ["webhook"]
