monolog:
    channels: ["webhook"]
    handlers:
        webhook_handler:
            level:    debug
            type:     service
            # CONFIG_DUPE_1 below
            id:       monolog.webhook_handler
            channels: ["webhook"]
