twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    globals:
        app_current_version: '%app_current_version%'
        app_user_support_email: '%env(CT_USER_SUPPORT_EMAIL)%'
        app_user_support_html: '%env(CT_USER_SUPPORT_HTML)%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'form/custom_types.html.twig'
        - 'bootstrap_3_layout.html.twig'
