version: '3.1'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        environment:
            SFAPP_NOT_PRODUCTION: "true"
        volumes:
            - ./:/app
#            - var:/app/var
        depends_on:
            - db
    nginx:
        image: nginx
        ports:
            - 8880:80
        volumes:
            - ./:/app:ro,cached
            - ./docker/app.nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: covid
            POSTGRES_DB: covid
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5433:5432

volumes:
    db_data:
#    var: