version: '3.1'

services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        environment:
            SFAPP_NOT_PRODUCTION: "true"
        volumes:
            - ./:/app:cached
            - var:/app/var
        depends_on:
            - db
    nginx:
        image: nginx
        ports:
            - 8880:80
        volumes:
            - ./:/app:ro,cached
            - ./docker/app.nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
    db:
        image: mariadb:10.4
        environment:
            MYSQL_ROOT_PASSWORD: covid
            MYSQL_DATABASE: covid
            MYSQL_USER: ctdbuser
            MYSQL_PASSWORD: covid
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306

volumes:
    db_data:
    var: